### ISSUE TITLE
Roadmap February

### ISSUE THREAD

**Issue by tzhangchi** [tzhangchi/AFFiNE-ghost#1]
- [x] Copy and Paste Insert Markdown
- [x] ecursive scan notes
- [x] write public enable as well https://app.affine.pro/public-workspace/jnJtogkzkcOLVYwR2c4b5/c63f307bba71493fb2773530874a119f
- [x] Refactoring code
