### ISSUE TITLE
March Roadmap

### ISSUE THREAD

**Issue by tzhangchi** [tzhangchi/AFFiNE-ghost#2]
- [ ] Support adding page cover
- [ ] Support adding page footer
- [ ] Support adding social share link ,such as Twitter
- [ ] Support auto invite muliti members
- [ ] Support AI writer api
